spring:
  application:
    name: cache.demo

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
    url: jdbc:postgresql://[::1]:5433/cache-demo-db
    # [::1] -> ipV6 connection to Db server or 127.0.0.1 || localhost  -> ipV4 connection to Db server !!!

  sql:
    init:
      mode: always

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        connection:
          pool_size: 100
        ################################
        ####### CACHING CONFIG #########
        ################################
        javax:
          cache:
            provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
            missing_cache_strategy: create
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          jakarta:
            persistence:
              sharedCache:
                mode: ENABLE_SELECTIVE # Mark entity classes with @Cacheable annotation!

logging:
  level:
    org.hibernate.sql: info

server:
  port: 9090
  servlet:
    context-path: "/api/v1"

cache:
  redis:
    props:
      host: "localhost"
      port: 6379


