version: '3.9'

services:
  postgres:
    container_name: cache-demo-db
    image: postgres:18beta3-alpine
    restart: on-failure
    env_file:
      - ../db_props.env
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      redis:

  redis-ui:
    image: redis/redisinsight
    container_name: redis-ui
    depends_on:
      - redis
    restart: always
    ports:
      - "8001:8001"
    networks:
      redis:

networks:
  redis:


